---
concurrency: <%= ENV['SIDEKIQ_CONCURRENCY'] || 5 %>
queues:
  - default
  - mailers
logfile: ./log/sidekiq.log
:schedule:
  notify_expired_rents:
    cron: '0 0 12 * * *'
    class: NotifyExpiredRentsJob
